name: Client CI

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - "Client/**"
      - .github/workflows/client-ci.yml

jobs:
  job1:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.x'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui-android

    - name: Build and Test
      run: |
        dotnet build ./Client -c Release
        dotnet test ./Client -c Release --logger trx

    - name: Publish Test Results
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Tests
        path: ./TestResults/*.trx
        reporter: dotnet-trx