name: Functions Deploy

on:
  workflow_dispatch:  
  push:
    branches:
      - master
      - dev
    paths:
      - "RankingServer/FunctionApp1/**"
      - .github/workflows/functions-deploy.yml

jobs:
  job1:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      FUNCTIONAPP_NAME : functk-dev-koreacentral-01
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.x'

    - name: Publish
      run: dotnet publish ./RankingServer/FunctionApp1 -c Release -o publish_output

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTIONAPP_NAME }}
        package: ./publish_output