name: Server CI

on:
  push:
    branches-ignore:
      - master
      - dev
    paths:
      - "Server/**"

jobs:
  job1:
    name: CI
    runs-on: ubuntu-latest

    env:
      SA_PASSWORD: sanklfj2045!@$#%jsj

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: ${{ env.SA_PASSWORD }}
          ACCEPT_EULA: "Y"
        options: >-
          --health-cmd "until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'sanklfj2045!@$#%jsj' -Q 'SELECT 1'; do sleep 1; done"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.x'

    - name: Wait for SQL Server to be ready
      run: |
        for i in {1..20}; do
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ env.SA_PASSWORD }} -Q "SELECT 1" && break
          sleep 5
        done

    - name: Build and Test
      run: |
        dotnet build ./Server -c Release
        dotnet test ./Server -c Release