name: WebServer CI

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - "WebServer/**"
      - .github/workflows/web-server-ci.yml

jobs:
  job1:
    name: CI
    runs-on: ubuntu-latest

    env:
      SA_PASSWORD: Strongsanklfj2045!@$#%jsjS

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          MSSQL_SA_PASSWORD: ${{ env.SA_PASSWORD }}
          ACCEPT_EULA: Y

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.x'

    - name: Build and Test
      run: |
        dotnet build ./WebServer -c Release
        dotnet test ./WebServer -c Release --logger trx
      
    - name: Publish Test Results
      uses: dorny/test-reporter@v2
      if: always()
      with:
        name: Tests
        path: ./WebServer/**/TestResults/*.trx
        reporter: dotnet-trx